name: gav
favicon: null
layout_spectrum: 0.7529540369287133
typography_spectrum: 0.7057678578421474
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.14595536631532013
  lightness: 0.6784007225651294
  saturation: 0.4209186297375709
  rhythmicContrast: 0.26057645794935524
purpose: []
